<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Nodify.Avalonia" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" />
    <PackageReference Include="FluentIcons.Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\samples\**" LinkBase="samples" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysmlStudio.Diagrams\SysmlStudio.Diagrams.csproj" />
    <ProjectReference Include="..\SysmlStudio.Editing\SysmlStudio.Editing.csproj" />
    <ProjectReference Include="..\SysmlStudio.Interchange\SysmlStudio.Interchange.csproj" />
  </ItemGroup>

</Project>
