<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SysmlStudio.App\SysmlStudio.App.csproj" />
  </ItemGroup>
</Project>
